<?php
require_once '../config/database.php';require_once '../config/auth.php';require_once '../eventos/helpers.php';
$u=requireAuth();requireCsrf();$empresa=(int)($_POST['empresa_id']??0);$tipo=strtoupper(trim($_POST['tipo']??'OUTRO'));$entTipo=strtoupper(trim($_POST['entidade_tipo']??''));$entId=(int)($_POST['entidade_id']??0);
if(!in_array($empresa,[1,2,3],true)||!usuarioTemAcessoEmpresa($conn,$u['id'],$empresa,$u['perfil']))jsonResponse(false,'Sem acesso à empresa.',[],403);
$tipos=['NFE','XML_NFE','ORCAMENTO','PROTOCOLO','COMPROVANTE','FOTO','OUTRO'];if(!in_array($tipo,$tipos,true))$tipo='OUTRO';
if(empty($_FILES['arquivo'])||$_FILES['arquivo']['error']!==UPLOAD_ERR_OK)jsonResponse(false,'Selecione um arquivo válido.',[],400);
$f=$_FILES['arquivo'];if((int)$f['size']>15*1024*1024)jsonResponse(false,'Arquivo excede 15 MB.',[],413);
$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($f['tmp_name'])?:'application/octet-stream';$allowed=['application/pdf','application/xml','text/xml','image/jpeg','image/png','image/webp','text/plain'];if(!in_array($mime,$allowed,true))jsonResponse(false,'Tipo de arquivo não permitido.',[],415);
$ext=['application/pdf'=>'pdf','application/xml'=>'xml','text/xml'=>'xml','image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','text/plain'=>'txt'][$mime]??'bin';$name=bin2hex(random_bytes(20)).'.'.$ext;$dir=realpath(__DIR__.'/../../storage/uploads');if(!$dir)jsonResponse(false,'Diretório de upload indisponível.',[],500);$dest=$dir.DIRECTORY_SEPARATOR.$name;if(!move_uploaded_file($f['tmp_name'],$dest))jsonResponse(false,'Não foi possível salvar o arquivo.',[],500);$sha=hash_file('sha256',$dest);$rel='storage/uploads/'.$name;$orig=substr(basename($f['name']),0,255);$size=(int)$f['size'];
$conn->begin_transaction();try{$s=$conn->prepare('INSERT INTO documentos(empresa_id,tipo,entidade_tipo,entidade_id,nome_original,arquivo,usuario_id,mime_type,tamanho_bytes,sha256) VALUES(?,?,NULLIF(?,\'\'),NULLIF(?,0),?,?,?,?,?,?)');$s->bind_param('ississisis',$empresa,$tipo,$entTipo,$entId,$orig,$rel,$u['id'],$mime,$size,$sha);$s->execute();$id=(int)$conn->insert_id;
criarEventoENotificar($conn,$empresa,$u['id'],'Documento enviado',$orig.' · '.$tipo,'INFORMATIVO','DOCUMENTO',$id,null,'DOCUMENTOS','DOCUMENTO_ENVIADO');registrarAuditoria($conn,$u['id'],$empresa,'ENVIAR_DOCUMENTO','DOCUMENTO',$id,$orig);$conn->commit();jsonResponse(true,'Documento enviado.',['documento_id'=>$id],201);}catch(Throwable $e){$conn->rollback();@unlink($dest);jsonResponse(false,'Erro ao registrar documento.',[],500);}
