USE bcmr;

CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(180) NOT NULL,
  cpf_cnpj VARCHAR(30) NULL,
  telefone VARCHAR(40) NULL,
  email VARCHAR(180) NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_cliente_doc(cpf_cnpj), INDEX idx_cliente_email(email)
);

ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_id BIGINT UNSIGNED NULL AFTER empresa_id;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER status;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS desconto DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER subtotal;

CREATE TABLE IF NOT EXISTS pedido_itens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL,
  produto_id INT UNSIGNED NOT NULL,
  quantidade INT NOT NULL,
  preco_unitario DECIMAL(12,2) NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  FOREIGN KEY(pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
  FOREIGN KEY(produto_id) REFERENCES produtos(id)
);

CREATE TABLE IF NOT EXISTS orcamentos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  empresa_id INT UNSIGNED NOT NULL DEFAULT 2,
  servico_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  descricao TEXT NULL,
  valor_mao_obra DECIMAL(12,2) NOT NULL DEFAULT 0,
  valor_pecas DECIMAL(12,2) NOT NULL DEFAULT 0,
  valor_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('RASCUNHO','ENVIADO','APROVADO','RECUSADO','CANCELADO') NOT NULL DEFAULT 'RASCUNHO',
  token_publico CHAR(64) NULL UNIQUE,
  enviado_em DATETIME NULL,
  respondido_em DATETIME NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(servico_id) REFERENCES servicos(id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id) REFERENCES empresas(id)
);

CREATE TABLE IF NOT EXISTS configuracoes (
  chave VARCHAR(120) PRIMARY KEY,
  valor TEXT NULL,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
